#!/bin/sh -eu

if test $# -ne 1; then
    echo "Usage: $0 TARGET_DIR" >&2
    exit 1
fi

scriptdir="$(dirname "$0")"
podman build -t raspi-netboot "$scriptdir"
podman unshare "$scriptdir/internal/export_btrfs" raspi-netboot "$1"
