#!/bin/sh -eu

case ${1-} in
    prereqs)
	echo
	exit 0
	;;
esac

if test "${nfsfile+x}"; then
    # Loop mounting over NFS 

    # Move NFS root out of the way
    mkdir /nfs
    mount -o move /root /nfs

    if test -f /keyfile; then
	# Encrypted root. Locking TODO
	cryptsetup --key-file=/keyfile open "/nfs/$nfsfile" root

	# Symlink root
	ln -s /dev/mapper/root /dev/net-root
    else
	if test "${nfscopy+x}"; then
	    lockargs="-c/nfs/$nfscopy"
	else
	    lockargs=
	fi

	# Lock and get loop device before mounting. Modprobe fails if
	# module is built-in.
	modprobe loop || true
	loopdev="`locknloop $lockargs -t 600 "/nfs/$nfsfile"`" || poweroff

	# Symlink root
	ln -s "$loopdev" /dev/net-root
    fi

    # Creating loop first since -o ro makes loop0 read-only otherwise
    mount -t btrfs -o ro /dev/net-root /root

    # Mark loop device as autoclear
    losetup -d "$loopdev"
    
    # Make NFS available in the system as /mnt/root/nfs
    mount -o move /nfs /root/mnt/root/nfs
else
    # QEMU environment

    # To keep emulated system similar to real one, obtain an IP this early
    dhclient || ipconfig eth0

    # Symlink root
    ln -s "$ROOT" /dev/net-root
fi
