#!/bin/sh -eu

LOCKNLOOP_HASH=6ed5ff97f65d8bac2e7ed6ce1b31885346f9b767

cd
git clone -n https://github.com/zouppen/locknloop.git
cd locknloop
git checkout "$LOCKNLOOP_HASH"
gcc -s -Wall -Os -o locknloop locknloop.c
