#!/bin/sh -eu

LOCKNLOOP_HASH=d127312e3b98630c4a04cd780cd8cbdbddc85fc0

cd
git clone -n https://github.com/zouppen/locknloop.git
cd locknloop
git checkout "$LOCKNLOOP_HASH"
klcc -s -static -o locknloop locknloop.c
