#!/bin/sh -eu

cleanup () {
    set +e
    trap - EXIT INT

    test "${root+x}" && umount "$root/boot"
    podman image umount "$image"
}

if test $# -ne 2 -o "$(whoami)" != root; then
    echo "Usage: podman unshare $0 PODMAN_IMAGE TARGET_DIR" >&2
    exit 1
fi

image="$1"
target="$2"
size=4G

trap cleanup EXIT INT

# Preparation
mkdir -p "$target"
root="$(podman image mount "$image")"

# Extract boot directory
rsync -a "$root/boot" "$target/"

# Create btrfs image without /boot directory contents
mount -t tmpfs hide "$root/boot"
mkfs.btrfs -b "$size" -r "$root" "$target/btrfs.img"
